language: python
python: 3.6
dist: trusty
addons:
  apt:
    packages:
      - ncbi-blast+
      - prodigal
install: pip3 install .
before_script: pip3 install codecov biopython
script: coverage run -m unittest
after_success: codecov
