name: hicap-env
channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.79
  - blast=2.5.0
  - boost=1.76.0
  - boost-cpp=1.76.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - csvtk=0.30.0
  - et_xmlfile=1.1.0
  - freetype=2.8.1
  - hicap=1.0.4
  - icu=68.2
  - jpeg=9e
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgfortran=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libsqlite=3.46.0
  - libstdcxx=14.1.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.2.0
  - libwebp-base=1.4.0
  - libzlib=1.2.13
  - ncurses=6.5
  - numpy=1.19.5
  - olefile=0.46
  - openpyxl=3.0.9
  - openssl=1.1.1w
  - pandas=1.1.5
  - pillow=5.2.0
  - pip=21.3.1
  - prodigal=2.6.3
  - python=3.6.15
  - python-dateutil=2.8.2
  - python_abi=3.6
  - pytz=2023.3.post1
  - readline=8.2
  - reportlab=3.4.0
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.46.0
  - tk=8.6.13
  - wheel=0.37.1
  - xz=5.6.3
  - zlib=1.2.13
  - zstd=1.5.6
