name: Hicap test workflow

on:
  workflow_dispatch:
  release:
    types: [created, published]

jobs:
  test-and-compare:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout current code
        uses: actions/checkout@v4

      # Step 2: Set up Conda with Mamba
      - name: Set up Conda with Miniforge3
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          use-mamba: true
          python-version: "3.6"
          activate-environment: base
          
      # Step 3: Create Conda environment using Mamba and YAML file
      - name: Create Conda environment from YAML
        shell: bash -el {0}
        run: |
          mamba env create -f environment.yml

      # Step 4: Activate the Conda environment
      - name: Activate Conda environment
        shell: bash -el {0}
        run: |
          conda activate hicap-env

      # Step 5: Check hicap version
      - name: Check hicap version
        shell: bash -el {0}
        run: hicap --version
