name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          conda-solver: "libmamba"
          python-version: "3.11"
          channels: bioconda,conda-forge,defaults
      - name: Conda install
        shell: bash -el {0}
        run: conda install 'python >=3.6' 'biopython >=1.79' 'reportlab ==3.4.0' 'prodigal >=2.6.1' 'blast >=2.2.28'
      - name: Unit tests
        shell: bash -el {0}
        run: python3 -m unittest
      - name: End-to-end test
        shell: bash -el {0}
        run: mkdir -p output/ && ./hicap-runner.py --query_fp example/Hi75.fasta --output_dir output/
